### ISSUE TITLE
Endless continouus reconcile loops

### ISSUE THREAD

**Issue by henninge** [moolen/harbor-sync#94]
**Kind**: BUG REPORT 

**Harbor Sync version**: 2.0.1

**Kubernetes version** (use `kubectl version`): 1.19.4

**Harbor version**: 2.3.1 (already present with 2.1.x)

**BUG REPORT**
Harbor-sync entered an endless loop of continouus reconciling which went as far as using up all CPU so that the readiness checck failed.

My investigations have shown that it is related to the number of harbor projects that a HarberSync config matches via its regex. In our case at around 18 matching requests the endless loop starts. Before that it is fine.

It is Friday night and I might not come up with a proof or solution now but my strong suspicion is that this happens because the status is updated on each and every loop. As a status update triggers another reconcile loop I always see two loops in a row on normal operation. If the second loop completes within the same second as the first the status update will write identical timestamps so that the status remains unchanged. No further reconcile loop is triggered. Once processing time goes above 1 second this is no longer true and we get continouus status updates.

**Comment by moolen** [comment]
This was fixed in #97.
